const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348135252741";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_11_10_17_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc2LFxuICAgICAgICA2MSxcbiAgICAgICAgODAsXG4gICAgICAgIDI4LFxuICAgICAgICAyMjUsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTIxLFxuICAgICAgICA5OSxcbiAgICAgICAgMzUsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTAsXG4gICAgICAgIDEyLFxuICAgICAgICAyMixcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMjgsXG4gICAgICAgIDIzOSxcbiAgICAgICAgODIsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTgyLFxuICAgICAgICAxOTYsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTc2LFxuICAgICAgICA0OCxcbiAgICAgICAgMjUxLFxuICAgICAgICAxNTAsXG4gICAgICAgIDMxLFxuICAgICAgICAxMjAsXG4gICAgICAgIDc3LFxuICAgICAgICAyNDAsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjUyLFxuICAgICAgICA3NVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNCxcbiAgICAgICAgMjAzLFxuICAgICAgICAxMDcsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjA4LFxuICAgICAgICA4MixcbiAgICAgICAgMzksXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjMwLFxuICAgICAgICAyNDksXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjA2LFxuICAgICAgICA0NixcbiAgICAgICAgMTMwLFxuICAgICAgICAxOTEsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTExLFxuICAgICAgICAyNixcbiAgICAgICAgMTAxLFxuICAgICAgICA1NCxcbiAgICAgICAgMjE0LFxuICAgICAgICAyMzQsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjAzLFxuICAgICAgICAxMDYsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTAyLFxuICAgICAgICA3LFxuICAgICAgICAxOTAsXG4gICAgICAgIDEyNSxcbiAgICAgICAgNDYsXG4gICAgICAgIDg1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjgsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTY2LFxuICAgICAgICA4MCxcbiAgICAgICAgNDIsXG4gICAgICAgIDQ0LFxuICAgICAgICAyNTAsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjQxLFxuICAgICAgICAxMjcsXG4gICAgICAgIDEyLFxuICAgICAgICAxODIsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMTMzLFxuICAgICAgICAyMjksXG4gICAgICAgIDIwNCxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMzYsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTU4LFxuICAgICAgICAyMjAsXG4gICAgICAgIDE5LFxuICAgICAgICAyMDIsXG4gICAgICAgIDg1LFxuICAgICAgICAyMTYsXG4gICAgICAgIDM4LFxuICAgICAgICAyOSxcbiAgICAgICAgMTY1LFxuICAgICAgICA3MSxcbiAgICAgICAgMTU1LFxuICAgICAgICAyMjksXG4gICAgICAgIDY2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDgyLFxuICAgICAgICAxMDcsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTE2LFxuICAgICAgICA2LFxuICAgICAgICAxMTYsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjI4LFxuICAgICAgICA1NixcbiAgICAgICAgMzAsXG4gICAgICAgIDMzLFxuICAgICAgICAxNDIsXG4gICAgICAgIDcsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTUzLFxuICAgICAgICA3NixcbiAgICAgICAgNzAsXG4gICAgICAgIDQ0LFxuICAgICAgICA5NixcbiAgICAgICAgOCxcbiAgICAgICAgMTY1LFxuICAgICAgICAxMjEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjEsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTQ4LFxuICAgICAgICA0NixcbiAgICAgICAgMTg0LFxuICAgICAgICA2OCxcbiAgICAgICAgMjA2LFxuICAgICAgICA3OSxcbiAgICAgICAgNTdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDk2LFxuICAgICAgICA5NSxcbiAgICAgICAgMTUyLFxuICAgICAgICAxODksXG4gICAgICAgIDE2OCxcbiAgICAgICAgMixcbiAgICAgICAgMzQsXG4gICAgICAgIDYyLFxuICAgICAgICAyOCxcbiAgICAgICAgMTg3LFxuICAgICAgICAzMyxcbiAgICAgICAgMTAsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTY5LFxuICAgICAgICAxOTYsXG4gICAgICAgIDEyNixcbiAgICAgICAgNSxcbiAgICAgICAgMTUxLFxuICAgICAgICAyNDgsXG4gICAgICAgIDE1MyxcbiAgICAgICAgODMsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjksXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjQxLFxuICAgICAgICAyMTUsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTU0LFxuICAgICAgICAxNDQsXG4gICAgICAgIDc1LFxuICAgICAgICAxMzMsXG4gICAgICAgIDk3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTIyLFxuICAgICAgICAxODMsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTUwLFxuICAgICAgICAxMjUsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTQwLFxuICAgICAgICAxMTQsXG4gICAgICAgIDQsXG4gICAgICAgIDkyLFxuICAgICAgICAyMDksXG4gICAgICAgIDE1MixcbiAgICAgICAgMjI3LFxuICAgICAgICAxNzEsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMjQzLFxuICAgICAgICA0OCxcbiAgICAgICAgODQsXG4gICAgICAgIDYwLFxuICAgICAgICA3LFxuICAgICAgICAxNzAsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjIyLFxuICAgICAgICA3NixcbiAgICAgICAgMTUwLFxuICAgICAgICAyMzAsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTEwLFxuICAgICAgICAxODYsXG4gICAgICAgIDE4OCxcbiAgICAgICAgNjFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICA0NyxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAyLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICA4MixcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgMTA2XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDksXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMzksXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICA1MixcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgMTkzLFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICA1MFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyMixcbiAgICAgICAgMjA0LFxuICAgICAgICAxNSxcbiAgICAgICAgOTgsXG4gICAgICAgIDYxLFxuICAgICAgICAxMTMsXG4gICAgICAgIDExLFxuICAgICAgICAyMjMsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjA5LFxuICAgICAgICA5MixcbiAgICAgICAgMTMwLFxuICAgICAgICA5NixcbiAgICAgICAgMjEyLFxuICAgICAgICAzOSxcbiAgICAgICAgMjQ3LFxuICAgICAgICA2NixcbiAgICAgICAgMzQsXG4gICAgICAgIDIxLFxuICAgICAgICAyMzUsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxODQsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTgzLFxuICAgICAgICA2MyxcbiAgICAgICAgMTI4LFxuICAgICAgICAxODQsXG4gICAgICAgIDEzLFxuICAgICAgICA3NCxcbiAgICAgICAgMTE4LFxuICAgICAgICA1NSxcbiAgICAgICAgODIsXG4gICAgICAgIDEzNixcbiAgICAgICAgMzcsXG4gICAgICAgIDg3LFxuICAgICAgICA4MixcbiAgICAgICAgMTM0LFxuICAgICAgICA4OSxcbiAgICAgICAgMTg2LFxuICAgICAgICAxOCxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNDgsXG4gICAgICAgIDg5LFxuICAgICAgICA5LFxuICAgICAgICAyMjgsXG4gICAgICAgIDE2MixcbiAgICAgICAgNzcsXG4gICAgICAgIDEzMyxcbiAgICAgICAgOSxcbiAgICAgICAgMTYsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTMsXG4gICAgICAgIDQwLFxuICAgICAgICAzMixcbiAgICAgICAgNTIsXG4gICAgICAgIDkyLFxuICAgICAgICAyMDYsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTEwLFxuICAgICAgICAyMzIsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTU5LFxuICAgICAgICAzXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxNDgsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwidVk3eWFUdGE1VFJUTWNIKzg4Q05PQWVtZGN2WTlWZkZyT1hqazZSZEZrZz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTM1MjUyNzQxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIxRDQ4MkZCMUZGQTY1N0QzRDBDMkFFQjJCRTEwNzRCMlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjkxNjcwNjJcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiejRvRGZ0bzhRUUNvMmRVajg3X2VjQVwiLFxuICBcInBob25lSWRcIjogXCJiNzcxMGU2MS1iMTBiLTQ5YjItOWJjYy1lOTc2NjAzN2Q0MzhcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTk4LFxuICAgICAgMTA4LFxuICAgICAgMjI1LFxuICAgICAgMixcbiAgICAgIDIwNCxcbiAgICAgIDE0LFxuICAgICAgMTczLFxuICAgICAgMTA5LFxuICAgICAgMjQyLFxuICAgICAgMyxcbiAgICAgIDE1NCxcbiAgICAgIDUyLFxuICAgICAgMjQxLFxuICAgICAgMjA2LFxuICAgICAgMTEzLFxuICAgICAgMTc4LFxuICAgICAgNTIsXG4gICAgICA4NCxcbiAgICAgIDEyNyxcbiAgICAgIDEzNFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4MyxcbiAgICAgIDE3LFxuICAgICAgMTM1LFxuICAgICAgMjAxLFxuICAgICAgMTQsXG4gICAgICAyMTUsXG4gICAgICA4MixcbiAgICAgIDc2LFxuICAgICAgNzMsXG4gICAgICAxNDMsXG4gICAgICAxMDUsXG4gICAgICAyMTgsXG4gICAgICAyNTEsXG4gICAgICA3MCxcbiAgICAgIDI4LFxuICAgICAgMTQ0LFxuICAgICAgNDcsXG4gICAgICAyMDUsXG4gICAgICAxNjYsXG4gICAgICAyMjNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiOTJYV0Q5QjZcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDgxMzUyNTI3NDE6NkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMTI0OTg3NDA3NDQ0MjE6NkBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNQeTZ6SVFCRU0vOXc3Z0dHQU1nQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIklMcnNrUkQ2WlJXaWVIVHVHTkhrZDlvNUsxVjl1SEdtNGdaSHdLeVlVMEE9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwidXFBMVNtVEdrL0xUUWZOVWpMZ3VJc091Y2psZGE0T0FKczZGQnNCMW1EVmJ1VHhocCtTdHFDcTRnRkJMcitNYWRWM3FMZWxWSmFSa2gxSjFTRTNGRHc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiNk1URk9TeDV5THByOFJBdEN2cjVxZWJrTFMvbFRSb0hOSjNqU3ZNUm9hYVVBbXgya1U1MnVtUENJS3MvMWpOM3o5aHBtZTB0NlpQYXVyUCs0OUdiRHc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0ODEzNTI1Mjc0MTo2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAyMSxcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAyMzgsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgNixcbiAgICAgICAgICA3MSxcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICA4MyxcbiAgICAgICAgICA2NFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI5MTY3MDU4LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRmZXXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFGZlcuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJKUE5YaUd6dldTRHV4TDc1M0lpbWNtb1BRTUdKNjFiYlJCeUtGZkxMS2hvPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjI3ODA3Njc5NixcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI4NDc2ODkzMTIwXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
